# COMP90024 Team 1
# Albert Darmawan (1168452) - darmawana@student.unimelb.edu.au
# Clarisca Lawrencia (1152594) - clawrencia@student.unimelb.edu.au
# I Gede Wibawa Cakramurti (1047538) - icakramurti@student.unimelb.edu.au
# Nuvi Anggaresti (830683) - nanggaresti@student.unimelb.edu.au
# Wildan Anugrah Putra (1191132) - wildananugra@student.unimelb.edu.au

version: "3.9"  # optional since v1.27.0
services:
    service:
        build:
            context: .
            dockerfile: ./services.Dockerfile
        image: wildananugrah/service
        deploy:
            mode: replicated
            replicas: 3
        environment:
            DBNAME: testdb
            DBHOST: http://admin:admin@115.146.95.84:25984/
        ports:
        - "8080:18080"
        networks:
        - net
    frontend:
        build:
            context: .
            dockerfile: ./frontend.Dockerfile
        image: wildananugrah/frontend
        deploy:
            mode: replicated
            replicas: 3
        ports:
            - "81:3000"
        networks:
            - net
    harvester:
        build:
            context: . 
            dockerfile: ./harvester.Dockerfile
        image: wildananugrah/harvester
        command: python -u /app/app.py
        environment:
            DBNAME: testdb
            DBHOST: "http://admin:admin@115.146.95.84:15984/"
            QUERY: jokowi
        labels:
            - "swarm.cronjob.enable=true"
            - "swarm.cronjob.schedule=* * * * *"
            - "swarm.cronjob.skip-running=false"
        networks:
            - net
networks:
    net: