version: "3.7"  # optional since v1.27.0
services:
  twitter_harvest:
    image: wildananugrah/twitter_collect
    environment:
      DB_NAME: comp90024_tweet_harvest
      ADDRESS: http://admin:admin@45.113.234.156:15984/
      API_TOKENS: /app/twitter-api-tokens.csv
      GEOJSON_ADDRESS: /app/cities_top50_simplified.geojson