version: "3.7"  # optional since v1.27.0
services:
  twitter_harvest:
    build:
        context: .
        dockerfile: ./Dockerfile
    image: wildananugrah/twitter_collect
    environment:
      DB_NAME: comp90024-team1-twitter-harvest-data
      ADDRESS: http://admin:admin@45.113.234.156:15984/
      API_TOKENS: /app/twitter-api-tokens.csv