version: "3.7"  # optional since v1.27.0
services:
  twitter_harvest:
    build:
      context: .
      dockerfile: ./harvester.Dockerfile
    image: wildananugrah/twitter_collect
    environment:
      DB_NAME: comp90024_tweet_harvest
      ADDRESS: http://admin:admin@45.113.235.136:15984/
      API_TOKENS: /app/twitter-api-tokens.csv
      GEOJSON_ADDRESS: /app/cities_top50_simplified.geojson
  twitter_search:
    build:
      context: .
      dockerfile: ./searcher.Dockerfile
    image: wildananugrah/twitter_search
    environment:
      DB_NAME: comp90024_tweet_search
      ADDRESS: http://admin:admin@45.113.235.136:15984/
      API_TOKENS: twitter-api-tokens.csv
      GEOJSON_ADDRESS: cities_top50_simplified.geojson
