### 
PUT http://admin:admin@127.0.0.1:5984/testdb/9da23705-64ae-4d56-a1ef-89b17fdeb002
Content-Type: application/json

{
    "username": "wildananugrah"
}

### 
GET http://admin:admin@127.0.0.1:5984/testdb/_all_docs?limit=10

###
POST http://admin:admin@127.0.0.1:5984/testdb/_find
Content-Type: application/json

{"selector": {"tweet_id": {"$eq": "1384682091342753795"}}}

###
POST http://admin:admin@127.0.0.1:5984/testdb/_find
Content-Type: application/json

{"selector": {},"limit": 10, "skip": 0}