version: "3.7"  # optional since v1.27.0
services:
  web:
    build:
        context: .
        dockerfile: ./Dockerfile
    image: service
    ports:
      - "8080:8080"
    networks:
      - comp90024_net
networks:
    comp90024_net: