version: "latest"
services:
  couch_master:
    image: "ibmcom/couchdb3:latest"
    restart: always
    ports:
      - "5984:5984"
      - "5986:5986"
      - "4369:4369"
      - "9100-9102:9100-9102"
    links:
      - couch_worker1
      - couch_worker2
    volumes:
      - ./data/master/data:/opt/couchdb/data
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
      - NODENAME=couchdb115.146.95.84
    container_name: couch_master
    networks:
      couchdb_nw:
        ipv4_address: 115.146.95.84

  couch_worker1:
    image: "ibmcom/couchdb3:latest"
    restart: always
    ports:
      - "15984:5984"
    volumes:
      - ./data/worker1/data:/opt/couchdb/data
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
      - NODENAME=couchdb45.113.235.136
    container_name: couch_worker1
    networks:
      couchdb_nw:
        ipv4_address: 45.113.235.136

  couch_worker2:
    image: "ibmcom/couchdb3:latest"
    restart: always
    ports:
      - "25984:5984"
    volumes:
      - ./data/worker2/data:/opt/couchdb/data
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
      - NODENAME=couchdb45.113.233.153
    container_name: couch_worker2
    networks:
      couchdb_nw:
        ipv4_address: 45.113.233.153