openapi: "3.0.0"
info:
  description: "Group 1 COMP90024 - IndoNerdz"
  version: "1.0.0"
  title: "Twitter Topic Analysis by IndoNerdz"
  contact:
    email: "nanggaresti@student.unimelb.edu.au"
tags:
- name: "topics"
  description: "All about trending topics"
- name: "demographics"
  description: "Retrieve aggregated data from AURIN"
paths:
  /topics:
    get:
      tags:
      - "topics"
      summary: "Finds trending topics in all areas"
      description: "Returns a list of trending topics everywhere"
      operationId: "getTopics"
      responses: 
        "200":
          description: "successful operation"
  /topics/{area_id}:
    parameters: [
  {name: "area_id",
      in: "path",
      description: "ID of area which trending topics are to be returned",
      required: true,
      schema: {
        $ref: '#/components/schemas/area_id'
    }
  }
]
    get:
      tags: [
  "topics"
]
      summary: "Find trending topics by area"
      description: "Returns a list of trending topics in an area"
      operationId: "getTopicsbyId"
      responses: 
        "200":
          description: "successful operation"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Topics not found"
components:
  schemas:
    area_id:
      properties:
        uuid:
          type: "string"
externalDocs:
  description: "Our repository"
  url: "https://github.com/darmawanalbert/comp90024-assignment2"